sudo: required

services:
  - docker

install:
  - docker build -t wakumaku/jitterbit_test .
  - docker run -d --name jitterbit_test -t wakumaku/jitterbit_test

script:
  - docker ps | grep -q jitterbit_test
  - ./.travis.sh